= AUTHENTICATION

There are several places where authentication is concerned.

The worker "`trusts`" the proxies, and trusts the channel between them.
This relies upon ZeroTier network authentication, and correct administrative
handling by the network owner, and is not dealt with further here.

The worker authenticates to either the local controller or to Central.
This is handled via the worker's local configuration file, which will
contain a "`secret`" value, corresponding either to an API token at
Central, or to the local secret used by the controller.  This is not
discussed further here.

Finally, and what we need to consider, is how do end-user/administrators
authenticate to the worker, so that the worker knows it can or should perform
the action on the user's behalf?

== Principles

. The proxy should be stateless, and have no idea about end-user credentials
. The proxy and the network between the proxy and the workers, is considered to
be authenticated and confidential (i.e. we need not worry about
man-in-the-middle attacks.
. Users may have different permissions, for different networks or for different
methods.
. We desire to enable the use of one-time passwords e.g. via OATH.
(Not to be confused with OAuth).
. We should support the use of API tokens (bearer tokens) for longer term uses.
. If API tokens are possible, they must be manageable.
. Whatever we do here needs to be extensible for the future (e.g. adding
further roles, time limits, etc.)
. The channel between the end-user/application and the proxy is encrypted via
TLS, which we trust (so we can use Basic auth).
. The end-user's authentication is between the end-user and the worker.
. Consequently, the same end user may have different credentials for different
workers.

== Basic Authentication

The most basic authentication, this method uses HTTP basic auth, with a
username and password.  If nothing else is configured, this must be available.

Requests to authenticate will be passed from the worker to the proxy as a 401
status, which will carry a little more detail in the `error` object (such
as the contents intended for the `WWW-Authenticate` header.

== API Token Authentication

In addition to user-based <<Basic Authentication>>, the system will also
support the creation and management of API Tokens.  API Tokens are
created on demand.  This may be done using `/token` API following
an OAuth 2.0 style, or it may be done in another way (e.g. via another
creation page).

It is not our intent to follow the full OAuth 2.0 flow with redirects, at
this time.  (That can be done later if time and needs dictate.)

API tokens are presented to the proxy via a "`Bearer`" style of HTTP
authentication.  Alternatively they may be presented via a custom
header.  See <<REST.adoc#>> for details.

API tokens also have an optional expiration.

During normal use of the primary API, only API tokens should be used.
(API tokens allocated once, and then discarded at the end, or with
a short lifetime.)

== One Time Passwords

For One Time Passwords, when appropriate, the same HTTP Basic Authentication
is used, but the supplemented with a one-time password presented in
a custom header.  See <<REST.adoc#>> for more details.

Because One Time Passwords are awkward to send with every request, applications
are going to want to use the OTP to allocate an API token, and then to
use that.

(NB: We *could* restrict which portions of the API require the OTP.  Right now
we require it for any password based authentication if a password is used
in lieu of a token.  Of course, none of this implemented yet.)

== Roles

We define some roles for permissions.

Proposed roles:

"token-admin":: can create new API tokens
"self-admin":: can change own password, provision or change OTP
"user-admin":: can create new users, manage user passwords, API tokens
"network-view":: can view network, including members
"network-admin":: can manage network, authorize, deauth members, etc.
"server-admin":: can restart the worker, etc.

In order to make it easy to pass around the list of authenticated
roles, and mask them, we limit the total number of roles to 64, so we
can use uint64_t to hold them as a bitmask.

Ultimately, roles and their meanings are chosen by the adminstrator.

Permission denied status is returned via 403 Forbidden, per HTTP/1.1.

NOTE: We should explore the idea of creating user "`groups`", so
that users can be a member of a group, and inherit the roles associated
with the group.  This would allow for much easier management of user
permissions, since an 'admin' group could then grant multiple permissions.
This would facilitate more fine grained permission models, by minimizing
the number of attributes (roles) that have to be manually assigned to
a single user.

== RPC Details

For authenticating to the worker, we will use the 401 Unauthorized code
as an error code, following standard HTTP/1.1 practices.

=== RPC Auth Parameter

For an API token, the token is self describing (long random string which
is a filename).  The file contains the details of the user and roles
for the token.

```
{ "auth": { "token": "757575757557575757" } }
```

For an initial password exchange:

```
{ "auth": { "user": "garrett", "pass": "maryhadalittlelamb" }}
```

We might wind up needing a one-time password.  In that case we might
have more structure, something like this:

```
{ "auth": {
	"user": "garrett",
	"pass": "maryhadalittlelamb",
	"otp": "abcdef"
	}
}
```

Note that OTP must always be used with the user's normal password as
well.  (Otherwise we lack the 2FA assurance).

The intention is that password and otp authentication are only used
to provision API tokens.  The otp mechanism will be required if
any otp is configured.

Errors from the RPC are allocated for various types of authentication
errors. See the <<RPC.adoc#>> document for details.

== Backing Store on Workers

The database of users and tokens are stored in directories by the
worker.  These are configurable as `userdir` and `tokendir`, and
may be the same directory if desired.

Users are stored in files named by the user, suffixed by `.usr`.
For example, `garrett` is stored in a file called `garrett.usr`.

Tokens are stored in files named with the token id, suffixed by `.tok`.

As a corollary, there are restrictions on usernames and token IDs,
since these need to be files.  We require that they not start with
a ., consist of legal filenames, and must be of reasonable length.
(Specific details are in the code.)

Roles are part of the master configuration file for the worker, as is
the configuration of what those permissions mean.

=== User Files

User files are interpreted as a single JSON object.
The following fields are defined and should always be present:

`name`:: User name.  This must match the filename, without the `.usr` suffix.
`passwd`:: Password.  This can be an empty string for no password, a string
starting with "0:" followed by a clear-text password, or "1:" followed
by a special salted SHA1 hash.  The salted form is used when changing
passwords or when using the API to create users, and protects against
in advertent password exposure to administrators.  The hashing algorithm
is not designed to thwart a determined attempt to crack the password,
so these files should still be access controlled.
`tag`:: This is a unique tag, and should be a random string.  This tag
will be used in token files as well, and prevents stale tokens from
accidentally being reassigned to users. (I.e. if a user is deleted and
recreated with the same name, the old token files should be invalid.)
`roles`: An array of role names.  These are the permissions that the user
can use.
`locked`: Boolean, if true the user cannot login or use any of their API tokens.
`otpwds`: This is an array of one-time-password generators. The members are
structures -- documentation TBD.

Other fields may be added, and will be ignored if not understood.

=== Token Files

Token files are also single JSON objects.
They have the following fields:

`id`:: Token ID.  This must match the token file name (without the `.tok` suffix).
`user`:: User name corresponding to the token.
`desc`:: A user supplied description for the token -- the intended use is for
display in UIs when listing tokens; this makes it easy to identify which
token should be deleted for example.
`tag`:: This tag must match the tag for the user.  (Token files that have
tags which don't match that of their named user are subject to deletion.)
`expires`:: A time in UNIX seconds when the token should expire.  If zero,
then the token does not expire.  (This is a number.)
`created`:: Time in UNIX seconds when the token was created.
`roles`:: An array of roles for this token.
The token can only be used for the named roles, which
may *only* include the roles available for the named user, and will be
a strict subset of the roles in effect at the time the token was created.
