= REST API

This protocol is offered by the proxy, and is how clients connect to
perform operations.

All operations are prefixed with a "`base URL`", which will be the hostname
and port (e.g. `http://example.com:9994`) followed by a standard URI prefix,
which is `/api/1.0/`.
All REST endpoints under this are assumed to conform to the API documented here.

All content exchanged over this protocol is in the form of JSON objects.

== Authentication

Authentication for controllers is unique to each controller, with
realm names based on the supplied controller name.
Hence, the `realm` returned in a `WWW-Authenticate:` response
401 header will be different depending which controller is being
addressed.

=== Basic Authentication

Normal HTTP Basic Authentication can be used, unless the user
has a two-factor device (one-time-password generator) configured.

=== Two-Factor Authentication

Two-factor authentication is based on OAth (not implemented yet),
and works just like HTTP Basic Authentication, except that an additional header, `X-ZTC-OTP` must be supplied.  This header
must contain the value of a one-time-password (typically a 6, 7, 8,
or 9 digit number) generated from the second factor.
The `Authorization:` header must still contain the user's Basic
authentication.

=== API Token Authentication

API tokens can be created (see API below) and used.  These may be
supplied as either "`Bearer`" tokens using the Bearer form of
`Authorization:` header, or they may be supplied in a seperate
`X-ZTC-Token:` header.

== API Endpoints

The following individual API endpoints and methods are defined.  We have
elided the `/api/1.0` prefix in the documentation below, but each URI
must include that prefix.


=== Controller Status

This obtains the status of the named controller (or central).

URI:: `/proxy/$controller/status`

Method:: `GET`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to query.
Body Parameters::
	None.

Result::
Object, with status from the server.

	`version`:::
	API version, "1.0" for now.
	Version numbers are strings, in "major.minor" form.
	These use semantic versioning, so the major number will be incremented
	when there are breaking changes to the API (with minor reset to zero),
	and the minor number is incremented when there are API changes that are
	non-breaking to older clients.
	`controller`:::
	true if the server is for a controller (bool)
	`central`:::
	true if the server is for central API server (bool)

=== Network List

This obtains the list of networks from the controller.

URI:: `/proxy/$controller/network`

Method:: `GET`

URI Parameters::
	`$controller`::: This is the name (or label) of of the controller to query.

Body Parameters::
	None.

Result::
	Array of networks serviced by controller, each element is
	a 16-digit hexadecimal string representing the network ID.

=== Get Network Object

This obtains the details of a given network from the controller.

URI:: `/proxy/$controller/network/$nwid`

Method:: `GET`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to query.
	`$nwid`::: This is the network ID, as a 16-digit decimal string.

Body Parameters::
	None.

Result::

	`id`::: The network ID (hexstring, 40-bit).
	`name`::: The network name (string).
	`private`::: Boolean, true if the network is private.
	`creationTime`::: Integer (msec since epoch) when network was created.
	`multicastLimit`::: Integer, limit on number of nodes to receive a multicast.
	`enableBroadcast`::: Boolean, true if broadcast is enabled.
	`v4AssignMode`::: Object, with booleans for IPv4 assignment modes.
	`v6AssignMode`::: Object, with booleans for IPv6 assignment modes.
	`routes`::: Array of IP routes to network members.

=== Get Network Member

This obtains details of a specific network member.

URI:: `/proxy/$controller/network/$nwid/member/$nodeid`

Method:: `GET`

URI Parameters::
	`$controller`::: This is name (or label) of the controller to query.
	`$nwid`::: This is the network ID, as a 16-digit decimal string.
	`$nodied`::: This is the node ID of the member, as a 10-digit decimal string.

Body Parameters::
	None.

Result::
	`id`::: The node ID, 16-digit hexadecimal (string).
	`nwid`::: The network ID, 10-digit hexidecimal (string).
	`authorized`::: true if the member is authorized (bool).
	`activeBridge`::: true if the member may bridge packets (bool).
	`revision`::: Member revision counter.
	`ipAssignments`::: Array of managed IP address assignments (strings).

=== Delete Network Member

This deletes a network member.

URI:: `/proxy/$controller/network/$nwid/member/$nodeid`

Method:: `DELETE`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.
	`$nwid`::: This is the network ID, as a 16-digit decimal string.
	`$nodied`::: This is the node ID of the member, as a 10-digit decimal string.

Body Parameters::
	None.

Result::
	Empty object.  (Perhaps instead a 204 No Content response?)

=== Authorize Network Member

This authorizes a network member.

URI:: `/proxy/$controller/network/$nwid/member/$nodeid/authorize`

Method:: `POST`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.
	`$nwid`::: This is the network ID, as a 16-digit decimal string.
	`$nodied`::: This is the node ID of the member, as a 10-digit decimal string.

Body Parameters::
	Empty object.

Result::
	Empty object.

=== Deauthorize Network Member

This deauthorizes a network member.

URI:: `/proxy/$controller/network/$nwid/member/$nodeid/deauthorize`

Method:: `POST`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.
	`$nwid`::: This is the network ID, as a 16-digit decimal string.
	`$nodied`::: This is the node ID of the member, as a 10-digit decimal string.

Body Parameters::
	Empty object.

Result::
	Empty object.


=== Create Authentication Token

This creates an authentication token.

URI:: `/proxy/$controller/token`

Method:: `POST`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.

Body Parameters::
	`roles`::: Array of strings of roles to grant to the token.
	This may elided, in which case all authorized roles will be granted.
	`expire`::: A time (number) in UNIX seconds when the token should expire.  The generated token may expire sooner at
	the server's discretion.
	`desc`::: A description for the token.

Result::
	`id`::: Generated token ID.  Use this with a Bearer authorization.
	`expire`::: The actual expiration time.
	`desc`::: Description of the token.

=== List Authentication Tokens

This returns a list of all the user's authentication tokens.

URI:: `/proxy/$controller/token`

Method:: `GET`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.

Body Parameters::
	None.

Result::
	Array of strings, each of which is a token ID corresponding to
	a token owned by the named user.

=== Delete Authentication Token

This delete an authentication token.

URI:: `/proxy/$controller/token/$id`

Method:: `POST`

URI Parameters::
	`$controller`::: This is the name (or label) of the controller to access.
	`$id`::: The authentication token to delete.

Body Parameters::
	None.

Result::
	Empty object.
