= RPC PROTOCOL

This protocol is used by the proxy to talk to individual workers.

== Operational Overview

The RPC protocol implemented using the NNG REQ/REP pattern.

The proxy opens a REQ socket and dials to a the worker's REP socket.
(Address discovery is handled in the SURVEY protocol, documented
elsewhere.)

The entire protocol uses the ZeroTier network, and specifically the
NNG ZeroTier transport, exclusively.

The protocol is a flavor (or perhaps subset) of JSON-RPC v2.0.
We only support normal single issue requests (no batching, and no
notifications.)  Furthermore, we only support "id" attributes that
are 64-bit non-zero values encoded as hexadecimal strings.
(E.g. "fff").  (We might want to investigate relaxing this later, but
as we control both sides of the protocol it seems reasonable for now.)
Requests always contain a "params" object, which is always an object (i.e.
we do not support positional parameters.)

We also play a little fast and loose with the protocol, where we cannot
decode the incoming request properly (or it fails to meet our above
limitations) may come back with a generic error object, and with
a zero ID attribute.  This only happens if the client sends a bad
request to the server, so it's entirely avoidable.  (Again we control
both sides.)

Request IDs are used to provide a level of idempotency for requests
that need it, such as blind create requests.  This prevents us from
creating mutiple objects when a create request is replayed due to a lost
packet, for example.

For responses, the proxy converts the "code" of any error object to the HTTP
status, and treats "message" as the status line.  If the code is outside
range of legal HTTP status codes (100 through 599) then we convert it to a
generic 500.

For a successful response, the proxy assumes HTTP status 200.  (We may want to
change this to do a 201 or a 204 in some cases.)

=== Controller Names

The controllers we talk to are "`named`".  The name is also known as a "`label`"
in the configuration file.  These names are used to identify the controller
(or central API) used to talk manage networks and members.  These are
composed of alphanumeric characters, or possibly dash (-) or underscore (_)
characters, of arbitrary length.  It is recommended that names adhere to
the rules for naming identifiers in C, or other common programming or scripting
languages.  (Specifcally forbidden are whitespace and most punctuation characters.)

=== Authentication

We support three different types of authentication (although at
this time only two are actually implemented.)

Within each RPC method, we will pass an `auth` object, which contains
the details for each of these.

For token based authentication, we can pass a bearer token using a
`token` member.  For this method, we don't need to pass any more
members, so it's just something like:

```
{ "auth": { "token": "<value>" }}
```

For user / password authentication we pass member fields of
`user` and `pass`, which are unsurprisingly the username and
password.

The third authentication method is just a refinement of the
above user / password authentication, and works the same, except
that a single one time password is added via a `otp` member.
(This must always be supplied with the member's actual password to
ensure that 2 factor authentication is used.  The one-time-password
is usually a 6-digit PIN coming from an Oath style TOTP or HOTP
generator.  Again this isn't implemented yet.)

In response to authentication errors, the code may reply with any
of these:

4010:: Authentication required (no authentication was supplied)
4011:: Authetication failed (well formed, but bad username, password)
4012:: Authentication requires a one-time-password.
4013:: Bearer token supplied is invalid (`token`).
4014:: Bearer token supplied has expired (`token`).

Generally, any of these will be accepted, except that when 2 factor
authentication is configured, then the `otp` value must be supplied.
If it is missing then 4012 will be sent.  Clients can use this to
discover the need for the user to submit a OTP using Google authenticator or somesuch.

== Method Definitions

The following individual methods are defined.
Note that in each section below, the "`Method`" is the `method` object of the
request, the "`Parameters`" are the `params` object, and the "`Result`" will
be the `result` object of a successful operation.

=== Controller Status

This obtains the status of the named controller (or central).

Method:: `status`

Parameters::
	`controller`:::  Controller name.

Result::
Object, with status from the server.

	`version`:::
	API version, "1.0" for now.
	Version numbers are strings, in "major.minor" form.
	These use semantic versioning, so the major number will be incremented
	when there are breaking changes to the API (with minor reset to zero),
	and the minor number is incremented when there are API changes that are
	non-breaking to older clients.
	`controller`:::
	true if the server is for a controller (bool)
	`central`:::
	true if the server is for central API server (bool)

=== Network List

This obtains the list of networks from the controller.

Method:: `get-networks`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::  Controller ID (hexstring, 40-bit).

Result::
	Array of networks serviced by controller, each element is
	a hexstring of the network ID.

=== Get Network Object

This obtains the details of a given network from the controller.

Method:: `get-network`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).

Result::
	`id`::: The network ID (hexstring, 40-bit).
	`name`::: The network name (string).
	`private`::: True if the network is private (bool).
	`creationTime`::: Integer (msec since epoch) when network was created.
	`multicastLimit`::: Integer, limit on number of nodes to receive a multicast.
	`enableBroadcast`::: Boolean, true if broadcast is enabled.
	`v4AssignMode`::: Object, with booleans for IPv4 assignment modes.
	`v6AssignMode`::: Object, with booleans for IPv6 assignment modes.
	`routes`::: Array of IP routes to network members.

=== Get Network Members

This obtains an array of members of the network.

Method:: `get-network-members`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).

Result::
	Aray of strings, each of which is a 10-digit hexadecimal
	node id, each of which is a member of the network.

=== Get Network Member

This obtains a single network member.

Method:: `get-network-member`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).
	`member`:::
		Member node ID (hexstring, 40-bit).

Result::
	`id`::: The node ID, 16-digit hexadecimal (string).
	`nwid`::: The network ID, 10-digit hexidecimal (string).
	`authorized`::: true if the member is authorized (bool).
	`activeBridge`::: true if the member may bridge packets (bool).
	`revision`::: Member revision counter.
	`ipAssignments`::: Array of managed IP address assignments (strings).

=== Delete Network Member

This deletes a single network member.

Method:: `delete-network-member`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).
	`member`:::
		Member node ID (hexstring, 40-bit).

Result::
	Empty object.

=== Authorize Network Member

This authorizes a single network member.

Method:: `authorize-network-member`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).
	`member`:::
		Member node ID (hexstring, 40-bit).

Result::
	Empty object.

=== Deauthorize Network Member

This deauthorizes a single network member.

Method:: `deauthorize-network-member`

Parameters::
	`auth`::: Current authentication credentials.
	`controller`:::
		Controller name.
	`network`:::
		Network ID (hexstring, 64-bit).
	`member`:::
		Member node ID (hexstring, 40-bit).

Result::
	Empty object.


=== List Authentication Tokens

This returns a list of all the user's authentication tokens.

Method:: `get-auth-tokens`

Parameters::
	`auth`::: Current authentication credentials.

Result::
	Array of strings, each of which is a token ID corresponding to
	a token owned by the named user.

=== Create Authentication Token

Method:: `create-auth-token`

Parameters::
	`auth`::: Current authentication credentials.
	`desc`::: Description for token (string).
	`expire`::: Optional expiration time (UNIX seconds) as number.  Can be 0 to mean no expiration.  (The service may elect a sooner expiration time.)
	`roles`::: Array of strings, each of which corresponds to a role that the user has.  If not supplied, the roles are
	inherited from the current authentication credentials.

Result:::
	`id`::: Token ID.  Use this as the `token` member.
	`desc`::: Supplied description, or generated one if not supplied.
	`expires`::: Expiration time (UNIX seconds).
	`created`::: Creation time (UNIX seconds).
	`roles`::: Array of roles actually assigned.

=== Get Authentication Token

This gets an authentication token for inspection.

Method:: `get-auth-token`

Parameters::
	`auth`::: Current authentication credentials.
	`token`::: Token ID to delete.

Result::
	`id`::: Generated token ID.  Use this with a Bearer authorization.
	`expires`::: The actual expiration time.
	`created`::: Creation time, in UNIX seconds.
	`desc`::: Description of the token.
	`roles`::: Array of strings for actual assigned roles.


=== Delete Authentication Token

Method:: `delete-auth-token`

Parameters::
	`auth`::: Current authentication credentials.
	`token`::: Token ID to delete.

Result:::
	Empty object.

=== Set Own Password

This changes the current user's password.

Method:: `set-password`

Parameters::
	`auth`::: Current authentication credentials.
	`password`::: New password.

Result::
	Empty object.

=== Configure a TOTP (time based one time password)

This resets the TOTP entry.  Note that at this time only a single
TOTP (time-based one time password) may be created per user.

Method:: `create-totp`

Parameters::
	`auth`::: Current authentication credentials.
	`issuer`::: Issuer to associate with the OTP.  (From proxy usually).

Result::
	`issuer`::: The name supplied in the call.
	`secret`::: base-32 secret (32 bytes, 160 bits)
	`digits`::: 6 (only 6 supported for now)
	`period`::: 30 (30 secs since epoch)
	`type`::: `totp`, for a time based OTP
	`algorithm`::: `SHA1` (no support for other algorithms)
	`url`::: `otpauth://` URL suitable for conversion to QR code.

=== Unconfigure TOTP (time based one time password)

This disables TOTP based authentication, restoring plain
username/password authentication.

Method:: `delete-totp`

Parameters::
	`auth`::: Current authentication credentials.

Result::
	Empty object.

=== Validate Configuration File

This validates that the configuration file is usable.
This is useful if the configuration file has been changed out of band.

Method:: `validate-config`

Parameters::
	`auth`::: Current authentication credentials.

Result::
	Empty object.
