= SURVEY Protocol

The survey protocol is used to allow the proxy to discover workers.

More correctly, it allows the worker to register a service address with
the proxy, as well as to identify which networks it is servicing.

The proxy opens a listening SURVEYOR, which the workers will dial to.
(The address of the proxy's surveyor port is the one thing that must be
known to workers in advance - in the future this might be published via
DNS or some other mechanism.)

The proxy sends a blank survey (we don't care about the payload) to each
worker (one broadcast) at periodic (configurable?) intervals.

The workers respond with a JSON object that has these members:

port:: int, the ZeroTier REQ/REP port
controllers:: array of controllers, where each is a string

For example:

```
{
        "port":  8456,
        "controllers": [ "corporate", "central" ]
}
```

The names of controllers are assigned by the application.
Note that the survey response must fit within a ZeroTier frame, so
a single worker will need to have a reasonable limit on the numnber
of controllers it exposes.

Note that the combination of the version and the ZT port can be read in
a single 32-bit operation, and as the version is currently zero the
resulting value can be used directly.

Also, the ZeroTier network and node ID of the worker will be the same
for both the SURVEY and the REP sockets, so they are not supplied in the
response.
